# Generated by Django 3.2.3 on 2022-09-09 09:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
